# Generated by Django 4.2.1 on 2023-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_answer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
