# Generated by Django 4.2.1 on 2023-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervariant',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='a', max_length=2),
            preserve_default=False,
        ),
    ]
