# Generated by Django 4.2.1 on 2023-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_answervariant_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='start', max_length=64),
        ),
    ]
