# Generated by Django 4.2.1 on 2023-05-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.question'),
        ),
    ]
