# Generated by Django 4.2.1 on 2023-05-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_answervariant_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltask',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoreticaltask',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.module'),
            preserve_default=False,
        ),
    ]
