# Generated by Django 4.2.1 on 2023-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_module_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiraissue',
            old_name='practical_task_id',
            new_name='practical_task',
        ),
        migrations.RenameField(
            model_name='jiraissue',
            old_name='theoretical_task_id',
            new_name='theoretical_task',
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='jira_key',
            field=models.CharField(default='QT-1', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='link',
            field=models.URLField(default='https://reqa.atlassian.net/browse/QT-2'),
            preserve_default=False,
        ),
    ]
