# Generated by Django 4.2.1 on 2023-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_practical_task_id_jiraissue_practical_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='chat_gpt_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='chat_gpt_rank',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='maximum_rank',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
