# Generated by Django 4.2.1 on 2023-05-14 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_jiraissue_chat_gpt_comment_jiraissue_chat_gpt_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 14, 8, 16, 20, 706996, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
